export const ROUTES = {
  HOME_PAGE: "/",
  DASHBOARD: "/dashboard",
  ORDER: "/order",
  ORDER_DETAIL: "/order_detail",
  CREATE_ORDER_OFF: "/create_order_offline",
  CREATE_ORDER_ON: "/create_order_online",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/product_detail/:id",
  ADD_PRODUCT: "/add_product",
  UPDATE_PRODUCT: "/update_product/:id",
  CATEGORY: "/categories",
  ADD_CATEGORY: "/add_category",
  UPDATE_CATEGORY: "/update_category",
  SETTING: "/setting",
  MESSAGES: "/messages",
  SIGNOUT: "/singout",
  USER: "/users",
  ADD_USER: "/add_user",
  UPDATE_USER: "/update_user",
};
