export const DASHBOARD = "DASHBOARD";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAILED = "DASHBOARD_FAILED";

export const STATIC_QUIZ = "STATIC_QUIZ";
export const STATIC_QUIZ_SUCCESS = "STATIC_QUIZ_SUCCESS";
export const STATIC_QUIZ_FAILED = "STATIC_QUIZ_FAILED";
